version: '3'

services:
    app:
        image: docker-build-apache
        container_name: docker-build-apache
        build:
            context: ./
            dockerfile: ./docker/php56/Dockerfile
        ports:
            - "80:80"
        volumes:
            - .:/var/www/html




